build:
    environment:
        mysql: false
        postgresql: false
        redis: false
        rabbitmq: false
        php:
            version: 7.0.8

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=logs/clover.xml'
                coverage:
                    file: 'logs/clover.xml'
                    format: 'php-clover'

checks:
    php:
        code_rating: true
        duplication: true
